Repository kubevirt/kubesecondarydns, pull requests merged in 2022-12, with the labels that each got.

#33 Add missing CNAO's CR manifest and bump kubevirt
  cluster/up.sh
  hack/cna/cna-cr.yaml
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm

#34 Add OWNERS file
  OWNERS
Labels: size/XS, release-note-none, dco-signoff: yes, lgtm

#24 Zone manager basic implementation - improvements
  pkg/zonemgr/zone_file.go
  pkg/zonemgr/zone_manager.go
Labels: approved, release-note-none, size/L, dco-signoff: yes, lgtm

#41 Cached and disk zone files renamed
  pkg/zonemgr/zone_file.go
  pkg/zonemgr/zone_file_cache.go
  pkg/zonemgr/zone_file_dns.go
  pkg/zonemgr/zone_manager.go
Labels: approved, release-note-none, size/L, dco-signoff: yes, lgtm

#35 git actions: Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, release-note-none, size/S, dco-signoff: yes, lgtm

#38 e2e, Introduce e2e test: resolving a FQDN entry
  cluster/cluster.sh
  cluster/up.sh
  go.mod
  go.sum
  hack/functest.sh
  pkg/controllers/controllers_suite_test.go
  tests/client.go
  tests/name_generator.go
  tests/test_suite_test.go
  tests/vm_generator.go
  tests/vm_startup_test.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/LICENSE
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/register.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/doc.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/register.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/types.go
  vendor/github.com/k8snetworkplumbingwg/network-attachment-definition-client/pkg/apis/k8s.cni.cncf.io/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apimachinery/pkg/util/rand/rand.go
  vendor/modules.txt
Labels: approved, release-note-none, dco-signoff: yes, lgtm, size/XXL

#43 tests, zone manager: Adding unit tests for zone manager component
  pkg/zonemgr/zone_file_cache.go
  pkg/zonemgr/zone_file_cache_test.go
  pkg/zonemgr/zone_file_test.go
  pkg/zonemgr/zone_manager.go
  pkg/zonemgr/zone_manager_test.go
  pkg/zonemgr/zonemgr_suite_test.go
Labels: approved, release-note-none, size/L, dco-signoff: yes, lgtm

#44 [e2e] adding a period to the tested fqdn and improve error readability
  tests/vm_startup_test.go
Labels: approved, size/XS, release-note-none, dco-signoff: yes, lgtm

#36 manifest: Change default values of env vars
  manifests/secondarydns.yaml
  tests/vm_startup_test.go
Labels: approved, size/XS, release-note-none, dco-signoff: yes, lgtm

#42 cnao: Use cached version
  cluster/up.sh
Labels: approved, release-note-none, size/S, dco-signoff: yes, lgtm

#47 cosmetics: Fix whitespace
  cluster/up.sh
Labels: approved, size/XS, release-note-none, dco-signoff: yes, lgtm

#48 kubevirt: Use latest stable release
  cluster/up.sh
Labels: approved, size/XS, release-note-none, dco-signoff: yes, lgtm

#37 readme: Update readme file
  README.md
  hack/whitespace.sh
  images/design.png
Labels: approved, release-note-none, size/L, dco-signoff: yes, lgtm

#49 Adding missing nameserver name to custom A record
  pkg/zonemgr/zone_file_cache.go
  pkg/zonemgr/zone_file_cache_test.go
Labels: approved, size/XS, release-note-none, dco-signoff: yes, lgtm

#50 Make secondary-dns deployment PSA ready
  README.md
  cluster/cluster.sh
  cluster/up.sh
  hack/create-nodeport.sh
  manifests/secondarydns.yaml
Labels: approved, release-note, size/S, dco-signoff: yes, lgtm

#52 controller: Move interface_filter to internal package
  pkg/controllers/internal/filter/filter_suite_test.go
  pkg/controllers/internal/filter/interface_filter.go
  pkg/controllers/internal/filter/interface_filter_test.go
  pkg/controllers/virtualmachineinstance_controller.go
Labels: size/M, approved, release-note-none, dco-signoff: yes, lgtm

#45 Handle status monitor container reload
  main.go
  pkg/zonemgr/zone_file.go
  pkg/zonemgr/zone_file_cache.go
  pkg/zonemgr/zone_file_cache_test.go
  pkg/zonemgr/zone_file_test.go
  pkg/zonemgr/zone_manager.go
  pkg/zonemgr/zone_manager_test.go
Labels: approved, release-note-none, size/L, dco-signoff: yes, lgtm
